package uk.co.corasoftware.enums;

public enum NodeType {

	NODEJS, TOMCAT, PHP_APACHE, PHP_LEMP, PHP_LITESPEED, PHP_NGINX, RUBY_NGINX, RUBY_APACHE, NET_CORE, PYTHON_APACHE,
	GOLANG, MONGODB, COUCHBASE, REDIS, MARIADB, MYSQL_CE, PERCONA, POSTGRESQL;

}